### ISSUE TITLE
Error Loading when  I launch Minecraft

### ISSUE THREAD

**Issue by Veilleur1206** [MarkusBordihn/BOs-Easy-NPC-Epic-Fight#10] opened 2024-04-23 06:05 UTC
I have the error : 	

![image](https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/164745687/10c0d7fe-eae0-4f0c-b45f-53fb9c2b6707)

(Sometimes it's with ZombieRenderer)

**To Reproduce**

Just install the following mods : 

![image](https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/164745687/1c65c9e0-290a-4346-a0ae-a1ba40993b32)

Minecraft version : 1.20.1
Forge version : 47.2.30

Then play

**Comment by Ph4i1ur3** [comment] 2024-04-26 17:01
Getting a similar error when on 1.18.2 with a Linux user, are you also on Linux?

**Comment by MarkusBordihn** [comment] 2024-04-27 08:48
Duplicate of #11

**Closed as completed by MarkusBordihn** 2024-04-27 08:48 UTC
Labels: bug, duplicate
