### ISSUE TITLE
[Feature Request] Can you update this mod?

### ISSUE THREAD

**Issue by fzrdwa123456** [MarkusBordihn/BOs-Easy-NPC-Epic-Fight#2] opened 2024-02-19 18:18 UTC
After I used weapons on epic fight NPCS, nothing worked except empty hand and sword and there was no animation. Can you fix this? And the drowning zombie model is broken, if you can add more NPCS to support epic battles thank you

**Comment by MarkusBordihn** [comment] 2024-04-09 18:21
Duplicate of #3 and #4.

Working currently on an updated version with additional supported models.

**Closed as completed by MarkusBordihn** 2024-04-09 18:21 UTC
Labels: duplicate, enhancement
